import "./globals.css";

export const metadata = {
  title: "TextuLearn",
  description: "Generated by Iqbal Hossen",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
