"use client";

import { useState } from "react";
import { FiChevronDown } from "react-icons/fi";

const FaqItem = ({ faq, isOpen, onClick }) => {
  return (
    <div className='border-b border-divider'>
      <button
        onClick={onClick}
        className='flex items-center justify-between w-full py-3 text-left focus:outline-none'
      >
        <h3 className='text-lg font-medium text-primary-dark'>
          {faq.question}
        </h3>
        <FiChevronDown
          className={`w-5 h-5 text-primary transform transition-transform duration-200 ${
            isOpen ? "rotate-180" : ""
          }`}
        />
      </button>
      <div
        className={`overflow-hidden transition-all duration-500 ease-in-out ${
          isOpen ? "max-h-screen opacity-100" : "max-h-0 opacity-0"
        }`}
      >
        <div className='pb-5 pr-10 '>
          <p className='text-base text-gray-700'>{faq.answer}</p>
        </div>
      </div>
    </div>
  );
};

const Faq = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      question: "What is TextuLearn?",
      answer:
        "TextuLearn is an AI-powered learning and writing assistant that helps you write better, faster, and smarter. It offers real-time grammar correction, paraphrasing, and writing improvement in over 50+ languages, plus access to 500+ curated educational books.",
    },
    {
      question: "Is TextuLearn free to use?",
      answer:
        "TextuLearn offers both free and premium plans. The free plan includes basic writing tools, while the premium plan unlocks advanced features like full book access, multilingual writing, and deeper content suggestions.",
    },
    {
      question: "Can I use TextuLearn for academic writing?",
      answer:
        "Yes! TextuLearn is perfect for academic writing, including essays, reports, summaries, and research assistance. Our tools help you generate clean, well-structured, and plagiarism-free content.",
    },
    {
      question: "How does TextuLearn help with language learning?",
      answer:
        "With support for 50+ languages and AI-powered writing correction, TextuLearn helps users improve their grammar, vocabulary, and fluency while writing in different languages.",
    },
    {
      question: "Is the content generated by TextuLearn plagiarism-free?",
      answer:
        "Yes. All content is generated uniquely by AI models to ensure originality. However, we always recommend a final review or check with a plagiarism tool for academic or official use.",
    },
    {
      question: "Can I access books offline?",
      answer:
        "Currently, books are accessible through the app while you're online. We are working on offline reading features for future updates.",
    },
    {
      question: "Is my personal data safe on TextuLearn?",
      answer:
        "Absolutely. We use end-to-end encryption and secure data storage to keep your information protected. Your writing data is not shared or stored without consent.",
    },
    {
      question: "How do I get started with TextuLearn?",
      answer:
        "Just sign up and start exploring! You can write, paraphrase, and learn instantly. No complex setup is required.",
    },
  ];

  const handleItemClick = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className='py-8 lg:py-16'>
      <div className='max-w-3xl px-4 mx-auto sm:px-6 lg:px-8'>
        <div className='text-center mb-4 relative'>
          <h2 className='text-3xl font-bold tracking-tight text-primary-dark sm:text-4xl'>
            Frequently Asked Questions
          </h2>
          <p className='mt-2 text-lg text-gray-600'>
            Find answers to common questions about TextuLearn.
          </p>
          <p className='text-outline text-6xl md:text-8xl lg:text-9xl font-bold text-center absolute left-1/2 -translate-x-1/2 z-0 select-none -top-10 opacity-30 pointer-events-none'>
            FAQ
          </p>
        </div>

        <div className='space-y-0'>
          {faqs.map((faq, index) => (
            <FaqItem
              key={index}
              faq={faq}
              isOpen={openIndex === index}
              onClick={() => handleItemClick(index)}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Faq;
